alias: parse-gate-question
automation_alias: script
automation_uid: 5b4e0237da074764
category: GATE Dataset Processing
deps:
deps:
- names: python
  tags: get,python3,
- names: python-lib
  tags: get,generic-python-lib,_pdfplumber
  tags: get,generic-python-lib,_requests
  tags: get,generic-python-lib,_python-dotenv
new_env_keys:
  - MLC_GATE_OUTPUT_JSON_PATH
new_state_keys:
  - questions
  - answers
tags:
  - parse-gate-question
  - parse
  - gate
  - questions
  - dataset
tests:
  run_inputs: []
input_mapping:
  question_pdf: MLC_GATE_QUESTION_PDF_PATH
  answer_pdf: MLC_GATE_ANSWER_PDF_PATH
  output_json: MLC_GATE_OUTPUT_JSON_PATH
  question_pdf_url: MLC_GATE_QUESTION_PDF_URL
  answer_pdf_url: MLC_GATE_ANSWER_PDF_URL
uid: 8fe2944512654e81
variations:
  gate:
    group: question-source
    default_variations:
      year: year.2025
    env:
      MLC_GATE_OUTPUT_JSON_PATH: '~/MLC/repos/local/cache/gate-exam-data/output.json'
